line-length = 150

[lint]
ignore = [
    "E401",  # Multiple imports on one line
    "E701",  # Multiple statements on one line (colon)
    "E702",  # Multiple statements on one line (semicolon)
    "E731",  # Do not assign a lambda expression
    "E722",  # Do not use bare except
    "E741",  # Ambiguous variable name
    "F541",  # f-string without any placeholders
]
