#!/usr/bin/env python3
"""
Lambda Cut Kdenlive Automation - Simplified
Generates Kdenlive project file with all assets.
"""

import os
import sys
import json
import glob
import subprocess
from datetime import datetime


# ==============================
# Configuration
# ==============================

FRAME_RATE = 25
ASS_STYLE = "Style: Default,Fira Sans Ultra,70.00,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,-1,0,0,0,100.00,100.00,0.00,0.00,1,10.00,11.00,5,40,40,71,1"

def find_base_project(workspace):
    """Find the Kdenlive project to use as template."""
    # First check templates folder
    templates_dir = os.path.join(workspace, "templates")
    if os.path.exists(templates_dir):
        projects = sorted(glob.glob(os.path.join(templates_dir, "*.kdenlive")))
        if projects:
            return projects[0]  # Return first template found
    
    # Fall back to output folder
    output_dir = os.path.join(workspace, "output")
    if os.path.exists(output_dir):
        projects = sorted(glob.glob(os.path.join(output_dir, "*.kdenlive")))
        if projects:
            return projects[-1]  # Return the latest
    return None


# ==============================
# Data Collection
# ==============================

def get_script_titles(workspace):
    scripts_dir = os.path.join(workspace, "scripts")
    titles = {}
    for script_file in sorted(glob.glob(os.path.join(scripts_dir, "script_*.txt"))):
        basename = os.path.basename(script_file)
        script_num = int(basename.replace("script_", "").replace(".txt", ""))
        with open(script_file) as f:
            first_line = f.readline().strip()
            if "Title:" in first_line:
                title = first_line.split("Title:", 1)[1].strip()
                if ":" in title:
                    title = title.split(":", 1)[1].strip()
            else:
                title = first_line
        titles[script_num] = title
    return titles


def get_tts_durations(workspace):
    tts_dir = os.path.join(workspace, "tts")
    durations = {}
    for wav_file in sorted(glob.glob(os.path.join(tts_dir, "tts_*.wav"))):
        basename = os.path.basename(wav_file)
        script_num = int(basename.replace("tts_", "").replace(".wav", ""))
        try:
            result = subprocess.run(
                ["ffprobe", "-v", "error", "-show_entries", "format=duration",
                 "-of", "default=noprint_wrappers=1:nokey=1", wav_file],
                capture_output=True, text=True, check=True
            )
            durations[script_num] = float(result.stdout.strip())
        except (subprocess.CalledProcessError, ValueError):
            durations[script_num] = 0
    return durations


def parse_srt_file(srt_file):
    subtitles = []
    if not os.path.exists(srt_file):
        return subtitles
    with open(srt_file) as f:
        content = f.read()
    blocks = content.strip().split("\n\n")
    for block in blocks:
        lines = block.strip().split("\n")
        if len(lines) >= 3:
            timing = lines[1].strip()
            if "-->" in timing:
                start_str, end_str = timing.split("-->")
                start = parse_srt_time(start_str.strip())
                end = parse_srt_time(end_str.strip())
                text = " ".join(lines[2:]).strip()
                subtitles.append({"start": start, "end": end, "text": text})
    return subtitles


def parse_srt_time(time_str):
    time_str = time_str.replace(",", ".")
    parts = time_str.split(":")
    return int(parts[0]) * 3600 + int(parts[1]) * 60 + float(parts[2])


def seconds_to_ass_time(seconds):
    hours = int(seconds // 3600)
    minutes = int((seconds % 3600) // 60)
    secs = seconds % 60
    centiseconds = int((secs % 1) * 100)
    secs = int(secs)
    return f"{hours}:{minutes:02d}:{secs:02d}.{centiseconds:02d}"


def seconds_to_frames(seconds):
    return int(seconds * FRAME_RATE)


def generate_ass_subtitles(workspace, script_titles, tts_durations):
    ass_content = []
    ass_content.append("[Script Info]")
    ass_content.append("; Script generated by Lambda Cut Kdenlive Automation")
    ass_content.append("LayoutResX: 1080")
    ass_content.append("LayoutResY: 1920")
    ass_content.append("PlayResX: 1080")
    ass_content.append("PlayResY: 1920")
    ass_content.append("ScaledBorderAndShadow: yes")
    ass_content.append("ScriptType: v4.00+")
    ass_content.append("WrapStyle: 0")
    ass_content.append("YCbCr Matrix: None")
    ass_content.append("")
    ass_content.append("[Kdenlive Extradata]")
    ass_content.append("MaxLayer: 0")
    ass_content.append("DefaultStyles: Default")
    ass_content.append("")
    ass_content.append("[V4+ Styles]")
    ass_content.append("Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding")
    ass_content.append(ASS_STYLE)
    ass_content.append("")
    ass_content.append("[Events]")
    ass_content.append("Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text")
    
    current_offset = 0
    for script_num in sorted(tts_durations.keys()):
        srt_file = os.path.join(workspace, "tts", f"tts_{script_num:03d}.srt")
        subtitles = parse_srt_file(srt_file)
        for sub in subtitles:
            start_time = current_offset + sub["start"]
            end_time = current_offset + sub["end"]
            start_ass = seconds_to_ass_time(start_time)
            end_ass = seconds_to_ass_time(end_time)
            ass_content.append(f"Dialogue: 0,{start_ass},{end_ass},Default,,0,0,0,,{sub['text']}")
        current_offset += tts_durations[script_num]
    
    return "\n".join(ass_content)


def generate_markers_json(script_titles, tts_durations):
    markers = []
    current_pos = 0
    for script_num in sorted(script_titles.keys()):
        if script_num in tts_durations:
            markers.append({
                "pos": seconds_to_frames(current_pos),
                "comment": script_titles[script_num],
                "duration": 0,
                "type": 0
            })
            current_pos += tts_durations[script_num]
    return json.dumps(markers)


# ==============================
# Main Entry Point
# ==============================

def generate_kdenlive_project(workspace):
    """Main function to generate Kdenlive project."""
    print("Lambda Cut Kdenlive Automation")
    print("=" * 50)
    
    # Find base project
    output_dir = os.path.join(workspace, "output")
    base_project = find_base_project(workspace)
    if not base_project:
        print(f"Error: No base project found in {output_dir}")
        return None
    
    print(f"Using base project: {os.path.basename(base_project)}")
    
    # Collect data
    print("\nCollecting data...")
    script_titles = get_script_titles(workspace)
    print(f"  Scripts found: {len(script_titles)}")
    
    tts_durations = get_tts_durations(workspace)
    print(f"  TTS files found: {len(tts_durations)}")
    
    if not script_titles or not tts_durations:
        print("Error: Missing required files (scripts or TTS)")
        return None
    
    total_duration = sum(tts_durations.values())
    print(f"  Total duration: {total_duration:.2f}s ({total_duration/60:.1f}m)")
    
    # Create output directory
    output_dir = os.path.join(workspace, "output")
    os.makedirs(output_dir, exist_ok=True)
    
    # Generate filenames with timestamp
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    project_file = os.path.join(output_dir, f"Shorts Project_{timestamp}.kdenlive")
    ass_file = os.path.join(output_dir, f"Shorts Project_{timestamp}.kdenlive.ass")
    
    # Generate markers
    markers_json = generate_markers_json(script_titles, tts_durations)
    print(f"  Generated {len(script_titles)} markers")
    
    # Generate ASS subtitles
    print("Generating ASS subtitles...")
    ass_content = generate_ass_subtitles(workspace, script_titles, tts_durations)
    with open(ass_file, "w") as f:
        f.write(ass_content)
    print(f"  Subtitles saved: {ass_file}")
    
    # Save base project as output, replacing old paths with new workspace
    with open(base_project, 'r') as f:
        content = f.read()
    
    # Replace markers/guides with new ones
    import re
    content = re.sub(r'<property name="kdenlive:sequenceproperties\.guides">.*?</property>', 
                      f'<property name="kdenlive:sequenceproperties.guides">{markers_json}</property>', content, flags=re.DOTALL)
    content = re.sub(r'<property name="kdenlive:markers">.*?</property>', 
                      f'<property name="kdenlive:markers">{markers_json}</property>', content, flags=re.DOTALL)
    
    # Replace known old paths with workspace (longest first)
    old_paths = [
        "/home/alph4r1us/Documents/Black-Mesa Laboratories/lambda-cut/Lambda Cut 2.1",
        "/home/alph4r1us/Documents/Black-Mesa Laboratories/lambda-cut",
        "/home/alph4r1us/lambda_cut",
    ]
    for old in old_paths:
        if old in content:
            content = content.replace(old, workspace)
    
    # Remove references to non-existent TTS and shorts files
    # Find all file references and remove chains for files that don't exist
    # Pattern: <chain ... </chain> blocks
    chain_pattern = re.compile(r'(<chain[^>]*>.*?</chain>)', re.DOTALL)
    
    # First pass: identify which chains to keep
    chains_to_keep = set()
    for match in chain_pattern.finditer(content):
        chain_content = match.group(1)
        resource_match = re.search(r'<property name="resource">([^<]+)</property>', chain_content)
        if resource_match:
            resource_path = resource_match.group(1)
            if os.path.exists(resource_path):
                chain_id_match = re.search(r'id="(chain\d+)"', chain_content)
                if chain_id_match:
                    chains_to_keep.add(chain_id_match.group(1))
    
    # Remove chains that reference non-existent files
    def keep_chain(match):
        chain_content = match.group(1)
        resource_match = re.search(r'<property name="resource">([^<]+)</property>', chain_content)
        if resource_match:
            resource_path = resource_match.group(1)
            if os.path.exists(resource_path):
                return chain_content
            else:
                return ''
        return chain_content
    
    content = chain_pattern.sub(keep_chain, content)
    
    # Remove playlist entries that reference removed chains
    # Pattern: <entry ... producer="chainX" ... /> (self-closing or not)
    entry_pattern = re.compile(r'<entry[^>]*producer="(chain\d+)"[^>]*/?>')
    
    def keep_entry(match):
        chain_ref = match.group(1)
        if chain_ref in chains_to_keep:
            return match.group(0)
        else:
            return ''
    
    content = entry_pattern.sub(keep_entry, content)
    
    # Debug: count entries after removal
    entry_count = content.count('<entry')
    print(f"DEBUG: Entry count after removal: {entry_count}")
    
    # Clean up ALL orphaned entries in playlists
    # Pattern: </entry> (with content) followed by <property>...</entry> (empty entry)
    lines = content.split('\n')
    result_lines = []
    i = 0
    while i < len(lines):
        line = lines[i]
        
        # Look for: </entry> then empty line then <property...>...</entry> (empty entry block)
        if line.strip() == '</entry>' and i + 3 < len(lines):
            next_line = lines[i + 1].strip()
            next_next_line = lines[i + 2].strip()
            next_next_next_line = lines[i + 3].strip() if i + 3 < len(lines) else ''
            if next_line == '' and 'kdenlive:id' in next_next_line and next_next_next_line == '</entry>':
                # Skip lines i+1, i+2, i+3 (empty + orphan + closing)
                i += 4
                continue
        
        result_lines.append(line)
        i += 1
    
    content = '\n'.join(result_lines)
    
    with open(project_file, 'w') as f:
        f.write(content)
    
    print(f"  Project saved: {project_file}")
    
    # Summary
    print("\n" + "=" * 50)
    print("Summary:")
    print(f"  Scripts: {len(script_titles)}")
    print(f"  TTS files: {len(tts_durations)}")
    print(f"  Total duration: {total_duration:.2f}s ({total_duration/60:.1f}m)")
    print(f"\nOutput files:")
    print(f"  {os.path.basename(project_file)}")
    print(f"  {os.path.basename(ass_file)}")
    
    return project_file


# ==============================
# CLI Entry Point
# ==============================

if __name__ == "__main__":
    # Get workspace from environment or use default
    workspace = os.environ.get("LAMBDA_CUT_WORKSPACE")
    if not workspace:
        script_dir = os.path.dirname(os.path.abspath(__file__))
        workspace = os.path.dirname(script_dir)
    
    generate_kdenlive_project(workspace)
